# Module manifest for module "FileDetails"
# Generated by: Mark-A-Dean (https://github.com/Mark-A-Dean)
# Generated on: 9/20/2024
@{
    RootModule="FileDetails.psm1";
    ModuleVersion="1.0.0";
    GUID=""; # use powershell to generate a GUID for your system
    Author="Mark-A-Dean";
    CompanyName="";
    Copyright="";
    Description="Loads required functions into memory for the extraction, transformation, and loading into a TSQL data table of file system metadata.";
    PowerShellVersion="5.1"; # 7.x capable, but retrograded for Windows PS 5.1 environments.
    #PowerShellHostName="Visual Studio Code Host";
    #PowerShellHostVersion="2024.2.2";
    PowerShellHostName="Windows PowerShell ISE Host";  # retrograded for Windows PS 5.1 environments.
    FunctionsToExport="*";
    CmdletsToExport=@("Get-FileDetails","New-ExceptionWindow","New-HashID","Update-BaseTable");
    VariablesToExport="*";
    #FileList=@("Get-FileDetails","New-ExceptionWindow","New-HashID","Update-BaseTable");
    PrivateData=@{
        PSData=@{
            Tags=@("file","inventory");
            ReleaseNotes="Initial release.";
        }
    }
# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix=""
}
